[build]
  base = "/"
  publish = "build/"
  command = "yarn build"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"

  # needs status to prevent changing on redirects
  status = 200