[build]
  base = "/"
  publish = "build/"
  command = "yarn build"
  functions = "lambda/"

# api -> redirect from non existing /api path to netlify functions
[[redirects]]
  from = "/api/*"
  to = "https://dns-lookup.netlify.app/.netlify/lambda/:splat"
  status = 200
  force = true